### ISSUE TITLE
With powershell terminal, this fails.

### ISSUE THREAD

**Issue by MariwanJ** [nils-soderman/vscode-batch-runner#3]
cmd: The term 'cmd' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

cmd is not defined inside powershell
and Visual Studio code uses powershell (Windows 10)

**Comment by nils-soderman** [comment]
Hi,

Thank you for reporting this issue!
This should now been fixed with the [v0.0.5](https://marketplace.visualstudio.com/items?itemName=NilsSoderman.batch-runner) release ([changelog](https://marketplace.visualstudio.com/items/NilsSoderman.batch-runner/changelog)).

Instead of using 'cmd' the extension will now use the absolute path to 'cmd.exe' _("C:\\windows\\System32\\cmd.exe" by default, can be changed in the user settings)_.

Cheers,
Nils
